# Generated by Django 5.2.9 on 2026-01-03 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi-Select')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/multiselect types')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('inverse_name', models.CharField(blank=True, help_text="Name when viewed from the other person's perspective", max_length=100)),
                ('category', models.CharField(choices=[('family', 'Family'), ('professional', 'Professional'), ('social', 'Social'), ('custom', 'Custom')], default='social', max_length=20)),
                ('is_symmetric', models.BooleanField(default=False, help_text='True if relationship is the same both ways (e.g., spouse, friend)')),
                ('auto_create_inverse', models.BooleanField(default=True, help_text='Automatically create inverse relationship')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('met_date', models.DateField(blank=True, null=True)),
                ('met_context', models.TextField(blank=True, help_text='How/where you met this person')),
                ('emails', models.JSONField(blank=True, default=list, help_text='List of {"email": "...", "label": "work/personal/..."}')),
                ('phones', models.JSONField(blank=True, default=list, help_text='List of {"phone": "...", "label": "mobile/home/..."}')),
                ('addresses', models.JSONField(blank=True, default=list, help_text='List of {"address": "...", "label": "home/work/..."}')),
                ('linkedin_url', models.URLField(blank=True)),
                ('discord_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, help_text='General notes about this person')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary')),
                ('ai_summary_updated', models.DateTimeField(blank=True, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='persons', to='core.group')),
                ('tags', models.ManyToManyField(blank=True, related_name='persons', to='core.tag')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('linkedin_synced', models.BooleanField(default=False)),
                ('linkedin_last_sync', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='people.person')),
            ],
            options={
                'verbose_name_plural': 'Employment history',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Anecdote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(help_text='Rich text / Markdown content')),
                ('date', models.DateField(blank=True, help_text='When this happened', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('anecdote_type', models.CharField(choices=[('memory', 'Memory'), ('joke', 'Joke'), ('quote', 'Quote'), ('note', 'Note')], default='note', max_length=20)),
                ('tags', models.ManyToManyField(blank=True, related_name='anecdotes', to='core.tag')),
                ('persons', models.ManyToManyField(related_name='anecdotes', to='people.person')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('date_taken', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_coords', models.JSONField(blank=True, help_text='{"lat": float, "lng": float}', null=True)),
                ('ai_description', models.TextField(blank=True, help_text='AI-generated description')),
                ('detected_faces', models.JSONField(blank=True, default=list, help_text='List of detected face regions for tagging assistance')),
                ('anecdote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='people.anecdote')),
                ('persons', models.ManyToManyField(blank=True, related_name='photos', to='people.person')),
            ],
            options={
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(help_text='Flexible storage for any field type')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='people.customfielddefinition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='people.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'definition'), name='unique_custom_field_per_person')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('strength', models.IntegerField(blank=True, help_text='Relationship strength 1-5', null=True)),
                ('auto_created', models.BooleanField(default=False, help_text='True if this was auto-created as inverse')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='people.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='people.person')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='people.relationshiptype')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('person_a', 'person_b', 'relationship_type'), name='unique_relationship'), models.CheckConstraint(condition=models.Q(('person_a', models.F('person_b')), _negated=True), name='no_self_relationship')],
            },
        ),
    ]
