# Generated by Django 5.2.10 on 2026-01-06 21:36

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fix encrypted field column types.

    The EncryptedTextField from encrypted_fields library stores data as bytea,
    but the initial migration created text columns. This converts them to bytea.
    """

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        # Person model encrypted fields
        migrations.RunSQL(
            sql="ALTER TABLE people_person ALTER COLUMN notes TYPE bytea USING notes::bytea;",
            reverse_sql="ALTER TABLE people_person ALTER COLUMN notes TYPE text USING notes::text;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE people_person ALTER COLUMN met_context TYPE bytea USING met_context::bytea;",
            reverse_sql="ALTER TABLE people_person ALTER COLUMN met_context TYPE text USING met_context::text;",
        ),
        # Employment model
        migrations.RunSQL(
            sql="ALTER TABLE people_employment ALTER COLUMN description TYPE bytea USING description::bytea;",
            reverse_sql="ALTER TABLE people_employment ALTER COLUMN description TYPE text USING description::text;",
        ),
        # Anecdote model
        migrations.RunSQL(
            sql="ALTER TABLE people_anecdote ALTER COLUMN content TYPE bytea USING content::bytea;",
            reverse_sql="ALTER TABLE people_anecdote ALTER COLUMN content TYPE text USING content::text;",
        ),
        # Relationship model
        migrations.RunSQL(
            sql="ALTER TABLE people_relationship ALTER COLUMN notes TYPE bytea USING notes::bytea;",
            reverse_sql="ALTER TABLE people_relationship ALTER COLUMN notes TYPE text USING notes::text;",
        ),
    ]
