# Generated by Django 5.2.9 on 2026-01-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_split_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='True if this is the CRM owner (you)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
