# Generated by Django 5.2.9 on 2026-01-03 21:20

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary'),
        ),
        migrations.AlterField(
            model_name='person',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='met_context',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', help_text='How/where you met this person (encrypted)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', help_text='General notes about this person (encrypted)'),
        ),
    ]
