# Generated by Django 5.2.9 on 2026-01-03 21:23

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_ai_summary_alter_person_discord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='description',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', help_text='Job description (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='met_context',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', help_text='How/where you met this person (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', help_text='General notes about this person (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='notes',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', help_text='Notes about this relationship (encrypted)', null=True),
        ),
    ]
